### ISSUE TITLE
transit.mov in the sketch folder ?

### ISSUE THREAD

**Issue by rich-gg** [omerjerk/processing-video-android#8]
Hi @omerjerk 

trying to run the GettingStartedMovie.pde example on nvidia K1 / Nougat, from Android Studio.
Crashing at startup.

I have tried placing the transit.mov file in an assets/ folder like I usually do and get
"MediaPlayer: start called in state 1, mPlayer(0x0)
...
FATAL EXCEPTION: GLThread 3406
"

Then I tried with the transit.mov file inside the sketch folder (as I read [here](https://forum.processing.org/two/discussion/13084/video-in-android-mode)) 
then I get more or less the same result
"
E/MediaPlayer: start called in state 1, mPlayer(0x0)
E/MediaPlayer: error (-38, 0)
E/MediaPlayer: Error (-38,0)
D/Grafika: Created program 3 (TEXTURE_EXT)
I/System.out: created surface texture
E/AndroidRuntime: FATAL EXCEPTION: GLThread 4066
                  Process: gg.rich.me.richmapping, PID: 26150
                  java.lang.RuntimeException: Framebuffer not complete, status=36054
                      at in.omerjerk.processing.video.android.VideoBase.prepareFrameBuffers(Unknown Source)
                      at in.omerjerk.processing.video.android.VideoBase$1.run(Unknown Source)
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1481)
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
"
Is it supposed to work ?

**Comment by kalwalt** [comment]
I have a similar issue running the video example:

>Initializing build sequence...
Deleted old build folder
Injected log broadcaster
video_android-dex.jar is mentioned in export.txt, but it's a big fat lie and does not exist.
Detected architecture arm64-v8a

>Packaging resources with AAPT...
Compiling with ECJ...

>Dexing with DX Dexer...
Merging DEX files with DX Merger...
Result compacted from 2848,3KiB to 1819,5KiB to save 1028,8KiB
Merged dex A (7 defs/8,0KiB) with dex B (1326 defs/2245,1KiB). Result is 1333 defs/1819,5KiB. Took 1,4s
Building APK file with APKBuilder...

>Signing and Zipaligning with ZipSigner...
Installing APK file...










>java.lang.NoClassDefFoundError: Failed resolution of: Lin/omerjerk/processing/video/android/Movie;
	at processing.test.gettingstartedmovie.GettingStartedMovie.setup(GettingStartedMovie.java:27)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.opengl.PGLES$AndroidRenderer.onDrawFrame(Unknown Source)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
Caused by: java.lang.ClassNotFoundException: Didn't find class "in.omerjerk.processing.video.android.Movie" on path: DexPathList[[zip file "/data/app/processing.test.gettingstartedmovie-2/base.apk"],nativeLibraryDirectories=[/data/app/processing.test.gettingstartedmovie-2/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 5 more
Failed to delete old APK file
i have a Wiko (View) Android Smartphone.
